### ISSUE TITLE
Query about the sparseconv

### ISSUE THREAD

**Issue by JoyHighmore** [yanx27/JS3C-Net#16]
Thank you for this brilliant work!

It seems that your code has already compile the sparseconvnet in the \lib, but I cannot import it. Could you please tell me how to import it?

I also tried the version from the original SparseConvNet repo from facebook, but it seems yours is a bit of different? It is said that _UNet got an unexpected keyword argument 'groups'_

Could you please tell more about how you use sparseconvnet?

Thx,
JH

**Comment by yanx27** [comment]
Hi, thanks for your interest! Did you compile the customized operators by `sh complile.sh` in `/lib`?

**Comment by yanx27** [comment]
For the `groups` parameter you can set it as `1` for original SparseConv

**Comment by JoyHighmore** [comment]
@yanx27 Yes, I followed all the steps in your instructions and I compile the compile.sh in /lib. It still says that UNet() got an unexpected keyword argument 'group'.

**Comment by JoyHighmore** [comment]
Hi! I've fixed the problem by  sh the egg-info file provided instead of from the original repo.

But there is another question about the SSC. It seems the input and output size of voxel is all 256x256x32. Is that meaning there is no completion but only the semantic segmentation for the voxels? I am so comfused.

Also, in the paper, you said, "by merging multiple frames in the Lidar sequences as supervision", can you explain more about that?

Thx,
JH

**Comment by yanx27** [comment]
@JoyHighmore Hi,  we firstly use SparseConv to obtain semantic segmentation result, which has the shape of NxC (N points C classes). After that, we voxelize the point cloud according to the below range and obtain volumetric with shape of 256x256x32. Since the point cloud is sparse, most of the voxels in the original volumetric  are 0, and it will be replaced as the nonzero number is the network to predict there is no empty (this process is called completion).

![image](https://user-images.githubusercontent.com/35829331/168722340-6df0b1db-9d1f-4297-ab06-0e66bc6c4ea3.png)

**Comment by JoyHighmore** [comment]
@yanx27 Thank you for the response! Just to comfirm, do you use the semantic_kitti_dense.cfg or semantic_kitti.cfg or settings.cfg to generate the ground truth? Could you please provide more details about the data preparation or probably a link that we could download? :)

Best,
JH

**Comment by yanx27** [comment]
Hi, @JoyHighmore, for the ground truth of SemanticKITTI, you can directly download from the official link as our mentioned. Also, the data preparation step is also shown in below.

![image](https://user-images.githubusercontent.com/35829331/169683260-63fe9687-a049-43c5-9a99-d440316434e5.png)
