### ISSUE TITLE
Spconv1.0 problem

### ISSUE THREAD

**Issue by yangchandler** [yanx27/JS3C-Net#9]
Hello, thank you very much for your work.

I have a problem compiling SPconv1.0 and have been unable to resolve it.

Could you please provide me with your compiled spconv1.0.whl?

Thank you very much

**Comment by adwiii** [comment]
Was there a specific resolution to this issue? I have also tried to install spconv1.0 using their directions, but am encountering issues (similar to [this](https://github.com/traveller59/spconv/issues/245)) when running the code. I am trying to resolve these in spconv, but because the issues and solution target newer versions, it is non-trivial to backport to v1.0.
